POST http://localhost:8080/idPwLogin
Content-Type: application/json

{
  "id": 999,
  "value": "content"
}

###

POST http://localhost:8080/test
Content-Type: application/json

{
  "id": 999,
  "value": "content"
}

###