DROP TABLE IF EXISTS CITY;

CREATE TABLE CITY (ID INT PRIMARY KEY AUTO_INCREMENT, NAME VARCHAR, COUNTRY VARCHAR, POPULATION INT);

INSERT INTO CITY (NAME, COUNTRY, POPULATION) VALUES ('San Francisco', 'US', 10000);
INSERT INTO CITY (NAME, COUNTRY, POPULATION) VALUES ('서울', 'KR', 20000);
INSERT INTO CITY (NAME, COUNTRY, POPULATION) VALUES ('東京', 'JP', 30000);
INSERT INTO CITY (NAME, COUNTRY, POPULATION) VALUES ('부산', 'KR', 40000);


DROP TABLE IF EXISTS USER_INFO;

CREATE TABLE USER_INFO (ID VARCHAR PRIMARY KEY, PW VARCHAR, NAME VARCHAR,IS_EXP BOOLEAN, IS_LOCK BOOLEAN, IS_ENABLE BOOLEAN, ROLE VARCHAR);

INSERT INTO USER_INFO (ID, PW , NAME, IS_EXP, IS_LOCK, IS_ENABLE, ROLE) VALUES ('myuoong', '1234' ,'박정웅', false,  false, true, 'USER');
INSERT INTO USER_INFO (ID, PW , NAME, IS_EXP, IS_LOCK, IS_ENABLE, ROLE) VALUES ('admin', '1234' ,'관리자', false,  false, true, 'ADMIN');